name: Print Working Directory

on:
  push:
    branches: [ main ]
 
jobs:
  print-pwd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Print working directory
      run: |
        pwd
        ls -la
